/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "additional-1": "var(--additional-1)",
        "brand-primary-pr01": "var(--brand-primary-pr01)",
        "brand-primary-pr02": "var(--brand-primary-pr02)",
        "brand-primary-pr06": "var(--brand-primary-pr06)",
        "brand-primary-pr08": "var(--brand-primary-pr08)",
        "brand-primary-pr09": "var(--brand-primary-pr09)",
        "brand-primary-pr10": "var(--brand-primary-pr10)",
        "brand-primary-pr11": "var(--brand-primary-pr11)",
        "primary-1": "var(--primary-1)",
        "primary-2": "var(--primary-2)",
        "secondary-1": "var(--secondary-1)",
        "secondary-2": "var(--secondary-2)",
        "tersier-1": "var(--tersier-1)",
        "tersier-2": "var(--tersier-2)",
        "variable-collection-7b7b7b": "var(--variable-collection-7b7b7b)",
        "variable-collection-chat-kolom": "var(--variable-collection-chat-kolom)",
        "variable-collection-cht-udh-d-baca": "var(--variable-collection-cht-udh-d-baca)",
        "variable-collection-darkgrey": "var(--variable-collection-darkgrey)",
        "variable-collection-grey": "var(--variable-collection-grey)",
        "variable-collection-pure-black": "var(--variable-collection-pure-black)",
      },
      fontFamily: {
        "body-1-bold": "var(--body-1-bold-font-family)",
        "body-1-regular": "var(--body-1-regular-font-family)",
        "body-1-semibold": "var(--body-1-semibold-font-family)",
        "body-2-bold": "var(--body-2-bold-font-family)",
        "body-2-regular": "var(--body-2-regular-font-family)",
        "body-2-semibold": "var(--body-2-semibold-font-family)",
        "body-3-bold": "var(--body-3-bold-font-family)",
        "body-3-regular": "var(--body-3-regular-font-family)",
        "body-3-semibold": "var(--body-3-semibold-font-family)",
        "caption-1-bold": "var(--caption-1-bold-font-family)",
        "caption-1-regular": "var(--caption-1-regular-font-family)",
        "caption-1-semibold": "var(--caption-1-semibold-font-family)",
        "caption-2-bold": "var(--caption-2-bold-font-family)",
        "caption-2-regular": "var(--caption-2-regular-font-family)",
        "caption-2-semibold": "var(--caption-2-semibold-font-family)",
        "display-1-bold": "var(--display-1-bold-font-family)",
        "display-1-regular": "var(--display-1-regular-font-family)",
        "display-1-semibold": "var(--display-1-semibold-font-family)",
        "display-2-bold": "var(--display-2-bold-font-family)",
        "display-2-regular": "var(--display-2-regular-font-family)",
        "display-2-semibold": "var(--display-2-semibold-font-family)",
        "heading-1-bold": "var(--heading-1-bold-font-family)",
        "heading-1-regular": "var(--heading-1-regular-font-family)",
        "heading-1-semibold": "var(--heading-1-semibold-font-family)",
        "heading-2-bold": "var(--heading-2-bold-font-family)",
        "heading-2-regular": "var(--heading-2-regular-font-family)",
        "heading-2-semibold": "var(--heading-2-semibold-font-family)",
        "heading-3-bold": "var(--heading-3-bold-font-family)",
        "heading-3-regular": "var(--heading-3-regular-font-family)",
        "heading-3-semibold": "var(--heading-3-semibold-font-family)",
        "heading-4-bold": "var(--heading-4-bold-font-family)",
        "heading-4-regular": "var(--heading-4-regular-font-family)",
        "heading-4-semibold": "var(--heading-4-semibold-font-family)",
        "heading-5-bold": "var(--heading-5-bold-font-family)",
        "heading-5-regular": "var(--heading-5-regular-font-family)",
        "heading-5-semibold": "var(--heading-5-semibold-font-family)",
        "heading-6-bold": "var(--heading-6-bold-font-family)",
        "heading-6-regular": "var(--heading-6-regular-font-family)",
        "heading-6-semibold": "var(--heading-6-semibold-font-family)",
        "heading-7-bold": "var(--heading-7-bold-font-family)",
        "heading-7-regular": "var(--heading-7-regular-font-family)",
        "heading-7-semibold": "var(--heading-7-semibold-font-family)",
        "heading-8-bold": "var(--heading-8-bold-font-family)",
        "heading-8-regular": "var(--heading-8-regular-font-family)",
        "heading-8-semibold": "var(--heading-8-semibold-font-family)",
        italiac: "var(--italiac-font-family)",
        "text-sm-medium": "var(--text-sm-medium-font-family)",
      },
      boxShadow: {
        "drop-shadow": "var(--drop-shadow)",
        "drop-shadow-2": "var(--drop-shadow-2)",
        "drop-shadow-3": "var(--drop-shadow-3)",
      },
    },
  },
  plugins: [],
};
